
ARG ALPINE_VERSION=3.21.0
FROM alpine:${ALPINE_VERSION} AS base
ARG NGINX_VERSION=1.28.0
# https://github.com/google/ngx_brotli
ARG NGX_BROTLI_COMMIT=a71f9312c2deb28875acc7bacfdd5695a111aa53

# https://github.com/google/boringssl
ARG BORINGSSL_COMMIT=a70ec8dd2cc1816e9deadda2f6e536640380e20c

# https://github.com/openresty/headers-more-nginx-module#installation
ARG HEADERS_MORE_VERSION=0.34

# https://github.com/leev/ngx_http_geoip2_module/releases
ARG GEOIP2_VERSION=3.4 

ARG CONFIG="\
		--build=$NGINX_VERSION \
		--prefix=/etc/nginx \
		--sbin-path=/usr/sbin/nginx \
		--modules-path=/usr/lib/nginx/modules \
		--conf-path=/etc/nginx/nginx.conf \
		--error-log-path=/var/log/nginx/error.log \
		--http-log-path=/var/log/nginx/access.log \
		--pid-path=/var/run/nginx.pid \
		--lock-path=/var/run/nginx.lock \
		--http-client-body-temp-path=/var/cache/nginx/client_temp \
		--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
		--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
		--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
		--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
		--user=nginx \
		--group=nginx \
		--with-http_ssl_module \
		--with-http_realip_module \
		--with-http_addition_module \
		--with-http_sub_module \
		--with-http_dav_module \
		--with-http_flv_module \
		--with-http_mp4_module \
		--with-http_gunzip_module \
		--with-http_gzip_static_module \
		--with-http_random_index_module \
		--with-http_secure_link_module \
		--with-http_stub_status_module \
		--with-http_auth_request_module \
		--with-http_xslt_module=dynamic \
		--with-http_image_filter_module=dynamic \
		--with-http_geoip_module=dynamic \
		--with-http_perl_module=dynamic \
		--with-threads \
		--with-stream \
		--with-stream_ssl_module \
		--with-stream_ssl_preread_module \
		--with-stream_realip_module \
		--with-stream_geoip_module=dynamic \
		--with-http_slice_module \
		--with-mail \
		--with-mail_ssl_module \
		--with-compat \
		--with-file-aio \
		--with-http_v2_module \
		--with-http_v3_module \
		--add-module=/usr/src/njs/nginx \
		--add-module=/usr/src/headers-more-nginx-module-$HEADERS_MORE_VERSION \
		--add-dynamic-module=/usr/src/ngx_brotli \
		--add-dynamic-module=/usr/src/ngx_http_geoip2_module \
	"
WORKDIR /usr/src/

# RUN \
#   apk add --no-cache --virtual .build-deps \
#     git \
#   # ngx_http_geoip2_module needs libmaxminddb-dev
#   && apk add --no-cache libmaxminddb-dev \
#   \
#   && git clone --depth 1 --branch ${GEOIP2_VERSION} https://github.com/leev/ngx_http_geoip2_module ngx_http_geoip2_module \
#   && apk del .build-deps

RUN \
	apk add --no-cache --virtual .build-deps \
		gcc \
		ca-certificates \
		coreutils \ 
		curl-dev \
		libstdc++ \
		libxml2-dev \
		lmdb-dev \ 
		libc-dev \
		make \
		musl-dev \
		go \
		ninja \
		openssl \
		git \
		pkgconfig \ 
		yajl-dev \
		zlib-dev \
		pcre-dev \
		linux-headers \
		curl \
		gnupg \
		libxslt-dev \
		libmaxminddb-dev \
		gd-dev \
		geoip-dev \
		perl-dev \
	&& apk add --no-cache --virtual .auth-jwt-build-deps \
		jansson-dev \
	&& apk add --no-cache --virtual .brotli-build-deps \
		autoconf \
		libtool \
		automake \
		git \
		g++ \
		cmake 

RUN \
	echo "Downloading nginx $NGINX_VERSION (from git release) ..." \
	&& wget https://github.com/nginx/nginx/releases/download/release-$NGINX_VERSION/nginx-$NGINX_VERSION.tar.gz -O /usr/src/nginx-$NGINX_VERSION.tar.gz \
	&& tar xzvf /usr/src/nginx-$NGINX_VERSION.tar.gz

RUN \
	echo "Cloning brotli $NGX_BROTLI_COMMIT ..." \
	&& mkdir /usr/src/ngx_brotli \
	&& cd /usr/src/ngx_brotli \
	&& git init \
	&& git remote add origin https://github.com/google/ngx_brotli.git \
	&& git fetch --depth 1 origin $NGX_BROTLI_COMMIT \
	&& git checkout --recurse-submodules -q FETCH_HEAD \
	&& git submodule update --init --depth 1

RUN \
  echo "Downloading headers-more-nginx-module ..." \
  && cd /usr/src \
  && wget https://github.com/openresty/headers-more-nginx-module/archive/refs/tags/v${HEADERS_MORE_VERSION}.tar.gz -O headers-more-nginx-module.tar.gz \
  && tar -xf headers-more-nginx-module.tar.gz

RUN \
  echo "Cloning ngx_http_geoip2_module ..." \
  && cd /usr/src \
  && git clone --depth 1 --branch ${GEOIP2_VERSION} https://github.com/leev/ngx_http_geoip2_module ngx_http_geoip2_module

RUN \
  echo "Cloning njs for nginx ..." \
  && cd /usr/src \
  && git clone https://github.com/nginx/njs \ 
  && cd njs \ 
  && ./configure \
  && make -j$(getconf _NPROCESSORS_ONLN)

RUN \	
  echo "Cloning auth_jwt ..." \
  && cd /usr/src \
  && git clone https://github.com/kjdev/nginx-auth-jwt 

RUN \
  echo "Cloning boringssl ..." \
  && cd /usr/src \
  && git clone https://boringssl.googlesource.com/boringssl \
  && cd boringssl \
  && echo "Building boringssl ..." \
  && cd /usr/src/boringssl \
  && mkdir build \
  && cd build \
  && cmake -DBUILD_SHARED_LIBS=1 -DBUILD_TESTING=off -GNinja .. \
  && ninja \
  && ls -la \
  && ls -la /usr/src/boringssl


RUN \
  echo "Building nginx ..." \
  && cd /usr/src/nginx-$NGINX_VERSION \
  && ./configure $CONFIG \
    --with-cc-opt="-I../boringssl/include"   \
    --with-ld-opt="-L../boringssl/build -lstdc++" \  
  && make -j$(getconf _NPROCESSORS_ONLN) \
  && make install \
	&& ls -la /usr/lib/nginx/modules \
	&& rm -rf /etc/nginx/html/ \
	&& mkdir /etc/nginx/conf.d/ \
	&& strip /usr/sbin/nginx* \
	&& strip /usr/lib/nginx/modules/*.so \
	\
	&& curl -fSL https://ssl-config.mozilla.org/ffdhe2048.txt > /etc/ssl/dhparam.pem \
	&& openssl req -x509 -newkey rsa:4096 -nodes -keyout /etc/ssl/localhost.key -out /etc/ssl/localhost.pem -days 365 -sha256 -subj '/CN=localhost' \
	\
	&& apk add --no-cache --virtual .gettext gettext \
	\
	&& scanelf --needed --nobanner /usr/sbin/nginx /usr/lib/nginx/modules/*.so /usr/bin/envsubst \
			| awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
			| sort -u \
			| xargs -r apk info --installed \
			| sort -u > /tmp/runDeps.txt \
  && apk del .brotli-build-deps .build-deps .auth-jwt-build-deps

FROM alpine:${ALPINE_VERSION}
COPY --from=base /usr/src/boringssl/build/*.so /usr/lib/
COPY --from=base /tmp/runDeps.txt /tmp/runDeps.txt
COPY --from=base /etc/nginx /etc/nginx
COPY --from=base /etc/ssl /etc/ssl
COPY --from=base /usr/lib/nginx/modules/*.so /usr/lib/nginx/modules/
COPY --from=base /usr/sbin/nginx /usr/sbin/
COPY --from=base /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/site_perl
COPY --from=base /usr/bin/envsubst /usr/local/bin/envsubst

RUN \
	addgroup -S nginx \
	&& adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
	&& apk add --no-cache --virtual .nginx-rundeps tzdata $(cat /tmp/runDeps.txt) \
	&& cat /tmp/runDeps.txt \
	&& apk add --no-cache libmaxminddb-dev \
                        libstdc++ \  
  && mkdir /var/log/nginx \
  && touch /var/log/nginx/access.log /var/log/nginx/error.log \
  && ln -sf /dev/stdout /var/log/nginx/access.log \
  && ln -sf /dev/stderr /var/log/nginx/error.log \
  && chgrp -R 0 /var/cache/nginx/ /var/log/ /var/run/ /etc/nginx/ \
  && chmod -R g=u /var/cache/nginx/ /var/log/ /var/run/ /etc/nginx/ \  
  && ln -s /usr/lib/nginx/modules /etc/nginx/modules \
  && mkdir -p /etc/nginx/certs \
  && ls -la /usr/lib \
  && ls -la /usr/lib/nginx/modules \
  && ldd /usr/sbin/nginx
  
COPY src/etc/nginx /etc/nginx

# show env
RUN env | sort
# test the configuration
RUN nginx -V; nginx -t; nginx -T;
EXPOSE 80 443
STOPSIGNAL SIGTERM
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
